project:
  type: website

website:
  title: "Katie Frank"
  open-graph: true
  navbar:
    right:
      - text: "Blog"
        file: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/katie-frank
      - icon: twitter
        href: https://twitter.com/katiexfrank
format:
  html:
    theme: minty
    css: styles.css

editor: visual

